### ISSUE TITLE
SYNTAX PROBLEM with 92 `rem` 10 ?

### ISSUE THREAD

**Issue by frranck** [learnyouanelm/learnyouanelm.github.io#22]
Hi,

in the Starting Out chapter

```
import Html

doubleMe x = x + x

main =
  Html.text (toString toPrint2)
  
toPrint2 =  92 `rem` 10
```

produces a syntax error...

**Comment by ghost** [comment]
Are you using Elm 0.18? Backticks (around `rem`) have been deprecated.

**Comment by JoeyEremondi** [comment]
LearnYouAnElm is incomplete, and has not been updated periodically.

In particular, the backticks syntax was removed in 0.18.

Pull requests are welcome, but if you're only interested in learning Elm, I recommend you start with the Elm guide: https://guide.elm-lang.org/

**Comment by frranck** [comment]
@willnwhite @JoeyEremondi OK thanks for the info.
