### ISSUE TITLE
Back-ticks reference in odd place in 04-syntax-in-functions.html

### ISSUE THREAD

**Issue by freking** [learnyouanelm/learnyouanelm.github.io#26]
Out of place back-tick reference. This paragraph is directly before "Let it be" section in 04-syntax-in-functions.html, but there are no infix functions near by. 

> Note: Not only can we call functions as infix with backticks, we can also define them using backticks. Sometimes it's easier to read that way.

Should this paragraph be deleted or moved after an infix function example?

**Comment by ebenpack** [comment]
Yeah, good call. I think this is some hangover from being forked from Learn You a Haskell, elm doesn't support arbitrarily infixing functions like this.
