### ISSUE TITLE
Chapter: 'Making your own classes' mentions typeclasses in headline

### ISSUE THREAD

**Issue by MarcusE1W** [learnyouanelm/learnyouanelm.github.io#36]
In the content the chapter is called: `Making your own classes` whereas in the actual chapter the headline is: `Making your own classes and typeclasses`. The `and typeclasses` should probably be dropped.

[link to chapter here](https://learnyouanelm.github.io/pages/08-making-our-own-types-and-typeclasses.html)

**Comment by ebenpack** [comment]
Yeah, that makes sense.
