### ISSUE TITLE
Anchor link in chapter 10 not working

### ISSUE THREAD

**Issue by tillydray** [learnyouanelm/learnyouanelm.github.io#38]
~There's a link~ There are (at least) 2 links in [chapter 10](https://learnyouanelm.github.io/pages/10-functionally-solving-problems.html), to the

- `folds` section in [Higher order functions](https://learnyouanelm.github.io/pages/06-higher-order-functions.html), and
- `composition` section also in Higher order functions

~the anchor link is both~ which are malformed. The current anchor links ~is~ are

- `https://learnyouanelm.github.io/pages/06-higher-order-functions/#folds`
- `https://learnyouanelm.github.io/pages/06-higher-order-functions#composition`

I tried several permutations but couldn't get it to work, otherwise I'd submit a PR. 

**EDIT:** added the second malformed anchor link after I discovered it.

**Comment by ebenpack** [comment]
Nice catches. These are both been fixed now. The markdown generated section headings also automatically generate an ID, so this 

    Function composition
    --------------------
    
    In mathematics, function composition is defined like this:

Generates this markup with the following section heading:
  
    <h2 id="function-composition">Function composition</h2>
    
    <p>In mathematics, function composition is defined like this:<p>

And you can link to this like:

    [point-free style](06-higher-order-functions#function-composition)

The other link also had a trailing slash.
