### ISSUE TITLE
Typo - Chapter Making Our Own Types 

### ISSUE THREAD

**Issue by tporcham** [learnyouanelm/learnyouanelm.github.io#49]
Hi,

I think there is a little typo in chapter "Making Our Own Types".

A type is defined as 
`type Shape = Circle Float Float Float | Rectangle Float Float Float Float `

The type signature is given as:

`> Circle
<function> : Float -> Float -> Float -> Shape
> Rectangle
<function> : Float -> Float -> Float -> Shape`

I think a Float is missing for the Rectangle constructor, so it should be:

`> Rectangle
<function> : Float -> Float -> Float -> Float -> Shape`

**Comment by ebenpack** [comment]
Yes, you're absolutely right! Would you like to make a PR for this?

**Comment by tporcham** [comment]
Created a pull request: https://github.com/learnyouanelm/learnyouanelm.github.io/pull/50
